line_length: 110
file_length:
  warning: 500
  error: 1200
  
disabled_rules: # rule identifiers turned on by default to exclude from running
  - multiple_closures_with_trailing_closure
  - force_cast
  - opening_brace
